name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTk0M2IzMGItOGFiMC00ZTM3LWJhZjItYTkwNjRhYmUwMGQ1IiwidGVuYW50X2lkIjoiOTI5NWJhOTYzMzFiYjJmNTRmNDM1OGUwMzc0ZmEwMTQyMTlhMDIzMjFkNGY2NGVjNjZiNjBiNThlOTc4ZTVmOSIsImludGVybmFsX3NlY3JldCI6IjU3N2NhODE0LTJmN2UtNGZiZC1iN2M3LWM2NDhiODM1ZDM1YSJ9.cKMI_qG4UURbNEFzM3quWrGUjDUMlK2hD4YBRxgKKlg"
JWT_SECRET='ahdhsndjk'

# Uncomment and configure these if needed:
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
